[project]
name = "mailwhisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.76",
    "langchain-ollama>=0.3.7",
    "pydantic>=2.11.7",
]
